# Generated by Django 4.2 on 2023-04-26 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iss_app", "0002_alter_location_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
