# Generated by Django 4.2 on 2023-05-01 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iss_app", "0005_alter_location_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notify",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notify",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
