# Generated by Django 4.2 on 2023-05-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iss_app", "0007_alter_notify_notify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notify",
            name="notify",
        ),
        migrations.AddField(
            model_name="notify",
            name="do_notify",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notify",
            name="last_notified",
            field=models.IntegerField(default=None),
        ),
    ]
