# Generated by Django 4.2 on 2023-05-02 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iss_app", "0008_remove_notify_notify_notify_do_notify_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notify",
        ),
    ]
